name: Specs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  verify:
    name: Specs
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: agendamento_covid_test
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true

      - name: Setup test database
        env:
          RAILS_ENV: test
          POSTGRESQL_HOST: localhost
          POSTGRESQL_PASSWORD: postgres
        run: |
          bundle exec rails db:setup

      - name: Run specs
        env:
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          POSTGRESQL_PASSWORD: postgres
          POSTGRESQL_HOST: localhost
          RAILS_ENV: test
        run: bundle exec rspec
